routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\SteamAuthController;
use App\Http\Controllers\Home\HomeController;
use App\Http\Controllers\Lan\LanController;
use App\Http\Controllers\Lan\Material\LanMaterialController;
use App\Http\Controllers\Lan\Material\MaterialController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return redirect()->route('users.lan');
});
Route::get('/', function () {
    return redirect()->route('users.lan');
});

Route::get('auth/steam', [SteamAuthController::class, 'redirectToSteam'])->name('auth.steam');
Route::get('auth/steam/handle', [SteamAuthController::class, 'handle'])->name('auth.steam.handle');
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::resources([
    'lans'  => LanController::class,
]);

Route::prefix('users')->group(function () {
    Route::get('games', [HomeController::class, 'games'])->name('users.games');
    Route::get('games/wishlist', [HomeController::class, 'wishlist'])->name('users.games.wishlist');
    Route::get('lan', [HomeController::class, 'lan'])->name('users.lan');
    Route::get('data/refresh', [HomeController::class, 'refreshDataUser'])->name('users.data.refresh');
});

Route::prefix('lans')->group(function () {
    Route::prefix('player')->group(function () {
        Route::post('search', [LanController::class, 'searchPlayer'])->name('lans.player.search');
        Route::post('vote/up', [LanController::class, 'upvoteGame'])->name('lans.player.vote.up');
        Route::post('vote/down', [LanController::class, 'downvoteGame'])->name('lans.player.vote.down');
        Route::post('points/add', [LanController::class, 'addPoint'])->name('lans.player.points.add');
        Route::post('points/remove', [LanController::class, 'removePoint'])->name('lans.player.points.remove');
        Route::post('points/reset', [LanController::class, 'resetPoints'])->name('lans.player.points.reset');
        Route::post('', [LanController::class, 'players'])->name('lans.players');
    });
});

Route::resource('materials', MaterialController::class);
Route::resource('lan_materials', LanMaterialController::class);

app/Models/User.php
<?php

namespace App\Models;

use App\Services\Steam\GameService;
use App\Services\Steam\UserService;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Throwable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $gameService;

    protected $userService;

    public function __construct()
    {
        $this->gameService = new GameService();
        $this->userService = new UserService();
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'steam_id',
        'avatar',
        'avatar',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function lans()
    {
        return $this->belongsToMany(Lan::class)->withPivot([
            'points'
        ])->orderByPivot('points');
    }

    public function games()
    {
        return $this->belongsToMany(Game::class)->withPivot([
            'playtime_forever',
            'playtime_windows_forever',
            'playtime_mac_forever',
            'playtime_linux_forever'
        ]);
    }

    public function votes()
    {
        return $this->hasMany(Vote::class);
    }

    public function getSteamGames()
    {
        return $this->gameService->getUserSteamGames($this);
    }

    public function getSteamAvatar()
    {
        $steam_api_key = env('STEAM_API_KEY');
        $url = 'http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=' . $steam_api_key . '&steamids=' . $this->steam_id;
        $response = Http::get($url);
        try {
            $playerData = $response->json()['response']['players'][0];
            $this->update(['avatar' => $playerData['avatar']]);
        } catch (Throwable $e) {
            Log::error($e);
            report($e);
        }
    }
}

resources/views/users/games.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>My games ({{ count($games) }}) <a href="{{ route('users.data.refresh') }}" class="sync"><small><i class="fas fa-sync-alt"></i></small></a></h2>
    <div class="row">
        @forelse($games->sortBy('name') as $game)
        <div class="col-12 col-sm-3">
            <div class="card mb-3">
                <h3 class="card-header" style="font-size: 1.1em;"><a href="https://store.steampowered.com/app/{{ $game->appid }}" target="_blank">{{ $game->name }}</a></h3>
                <img style="width: 100%; display: block;" src="http://media.steampowered.com/steamcommunity/public/images/apps/{{ $game->appid }}/{{ $game->img_icon_url }}.jpg" alt="{{ $game->name }}">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Playtime : {{ $game->pivot->playtime_forever }} min</li>
                    @if($game->discount_percent == null || $game->discount_percent == 0)
                    <li class="list-group-item">Price : {{ $game->final_formatted }}</li>
                    @else
                    <li class="list-group-item">Discount : {{ $game->discount_percent }} %</li>
                    <li class="list-group-item">Initial price : {{ $game->initial_formatted }}</li>
                    <li class="list-group-item">Final Price : {{ $game->final_formatted }}</li>
                    @endif
                </ul>
            </div>
        </div>
        @empty
        @endforelse
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('.sync').on('click', function() {
        showLoading();
    });
</script>
@endsection

resources/views/users/lan.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Your LAN</h2>
    <a href="{{ route('lans.create') }}" class="btn btn-primary">Create a new LAN</a>
    <br><br>
    <div class="row">
        @forelse($lans->sortBy('name') as $lan)
        <div class="col-12 col-sm-4">
            <div class="card mb-3">
                <h3 class="card-header" style="font-size: 1.1em;">{{ $lan->name }}
                    <a href="{{ route('lans.edit', $lan) }}"><small><i class="fas fa-pencil-alt"></i></small></a>
                    <form action="{{ route('lans.destroy', $lan) }}" class="d-inline-block" method="POST" style="float: right;">
                        {{ method_field('DELETE') }}
                        @csrf
                        <a onclick="this.closest('form').submit();return false;"><i class="fas fa-times"></i></a>
                    </form>
                </h3>
                <div class="card-body">
                    <p>{!! $lan->description ?? '<i>No description yet</i>' !!}</p>
                </div>
                <ul class="list-group list-group-flush">
                    @forelse($lan->users as $user)
                    <li class="list-group-item"><img src="{{ $user->avatar }}" alt="{{ $user->name }}"> <a href="https://steamcommunity.com/profiles/{{ $user->steam_id }}/" target="_blank">
                            {{ $user->name }}</a></li>
                    @empty
                    @endforelse
                </ul>
                <div class="card-body">
                    <a href="{{ route('lans.show', $lan) }}" class="btn btn-primary card-link show_lan">Show LAN</a>
                </div>
                <div class="card-footer text-muted">
                    {{ ucfirst($lan->date_start->translatedFormat('d F Y')) }} to {{ ucfirst($lan->date_end->translatedFormat('d F Y')) }}
                </div>
            </div>
        </div>
        @empty
        <div class="col-12 col-sm-4">
            <h4>Francis ?</h4>
            <blockquote class="blockquote">
                <p class="mb-0">WTF man ?! Where is Francis</p>
                <footer class="blockquote-footer">A very sad gamer :(</cite></footer>
            </blockquote>
        </div>
        @endforelse
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('.show_lan').on('click', function() {
        showLoading();
    });
</script>
@endsection

resources/views/users/wishlist.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>My wishlist ({{ count($wishlist) }})</h2>
    <div class="row">
        @forelse($wishlist->sortBy('name') as $game)
        <div class="col-12 col-sm-3">
            <div class="card mb-3">
                <h3 class="card-header" style="font-size: 1.1em;"><a href="https://store.steampowered.com/app/{{ $game->appid }}" target="_blank">{{ $game->name }}</a></h3>
                <img style="width: 100%; display: block;" src="{{ $game->img_icon_url }}" alt="{{ $game->name }}">
                <ul class="list-group list-group-flush">
                    @if($game->discount_percent == null || $game->discount_percent == 0)
                    <li class="list-group-item">Price : {!! $game->final_formatted !!} </li>
                    @else
                    <li class="list-group-item">Discount : {{ $game->discount_percent }} %</li>
                    <li class="list-group-item">Initial price : {{ $game->initial_formatted }}</li>
                    <li class="list-group-item">Final Price : {{ $game->final_formatted }}</li>
                    @endif
                    <li class="list-group-item">
                    @forelse ($game->tags as $tag)
                        <span class="badge badge-secondary">{{ $tag }}</span>
                    @empty
                    @endforelse
                    </li>
                </ul>
            </div>
        </div>
        @empty
        @endforelse
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('.sync').on('click', function() {
        showLoading();
    });
</script>
@endsection