routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\SteamAuthController;
use App\Http\Controllers\Home\HomeController;
use App\Http\Controllers\Lan\LanController;
use App\Http\Controllers\Lan\Material\LanMaterialController;
use App\Http\Controllers\Lan\Material\MaterialController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return redirect()->route('users.lan');
});
Route::get('/', function () {
    return redirect()->route('users.lan');
});

Route::get('auth/steam', [SteamAuthController::class, 'redirectToSteam'])->name('auth.steam');
Route::get('auth/steam/handle', [SteamAuthController::class, 'handle'])->name('auth.steam.handle');
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::resources([
    'lans'  => LanController::class,
]);

Route::prefix('users')->group(function () {
    Route::get('games', [HomeController::class, 'games'])->name('users.games');
    Route::get('games/wishlist', [HomeController::class, 'wishlist'])->name('users.games.wishlist');
    Route::get('lan', [HomeController::class, 'lan'])->name('users.lan');
    Route::get('data/refresh', [HomeController::class, 'refreshDataUser'])->name('users.data.refresh');
});

Route::prefix('lans')->group(function () {
    Route::prefix('player')->group(function () {
        Route::post('search', [LanController::class, 'searchPlayer'])->name('lans.player.search');
        Route::post('vote/up', [LanController::class, 'upvoteGame'])->name('lans.player.vote.up');
        Route::post('vote/down', [LanController::class, 'downvoteGame'])->name('lans.player.vote.down');
        Route::post('points/add', [LanController::class, 'addPoint'])->name('lans.player.points.add');
        Route::post('points/remove', [LanController::class, 'removePoint'])->name('lans.player.points.remove');
        Route::post('points/reset', [LanController::class, 'resetPoints'])->name('lans.player.points.reset');
        Route::post('', [LanController::class, 'players'])->name('lans.players');
    });
});

Route::resource('materials', MaterialController::class);
Route::resource('lan_materials', LanMaterialController::class);

app/Models/Lan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Lan extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'date_start',
        'date_end',
        'description',
    ];

    protected $casts = [
        'date_start' => 'datetime',
        'date_end' => 'datetime'
    ];

    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot([
            'points'
        ]);
    }

    public function votes()
    {
        return $this->hasMany(Vote::class);
    }
}

app/Http/Controllers/Lan/Game/VoteController.php
<?php

namespace App\Http\Controllers\Lan\Game;

use App\Http\Controllers\Controller;
use App\Models\Vote;
use Illuminate\Http\Request;

class VoteController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Vote  $vote
     * @return \Illuminate\Http\Response
     */
    public function show(Vote $vote)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Vote  $vote
     * @return \Illuminate\Http\Response
     */
    public function edit(Vote $vote)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Vote  $vote
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vote $vote)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Vote  $vote
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vote $vote)
    {
        //
    }
}

app/Http/Controllers/Lan/LanController.php
<?php

namespace App\Http\Controllers\Lan;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreLanRequest;
use App\Models\Lan;
use App\Models\LanMaterial;
use App\Models\User;
use App\Models\Vote;
use App\Services\Steam\GameService;
use App\Services\Steam\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class LanController extends Controller
{

    private $userService;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->userService = new UserService();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $friendlist = $this->userService->getSteamUserFriendlist(Auth::user());
        $data = [
            'friendslist' => $friendlist
        ];
        return view('lans.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreLanRequest $request)
    {
        $lan = new Lan($request->all());
        $lan->save();
        $lan->users()->attach(Auth::user());
        $players = explode(',', $request->players);
        if (!empty($players[0])) {
            foreach ($players as $player) {
                $user = User::where('steam_id', $player)->first();
                // user doesn't exists in db
                if ($user === null) {
                    $steamUser = $this->userService->getSteamUsersData($player);

                    // create user
                    $user = new User();
                    $user->name = $steamUser[0]['personaname'];
                    $user->avatar = $steamUser[0]['avatar'];
                    $user->steam_id = $steamUser[0]['steamid'];
                    $user->save();

                    // load user's data
                    $user->getSteamGames();
                }
                if (!$lan->users->contains($user)) {
                    $lan->users()->attach($user);
                }
            }
        }

        // update all games price
        // $gameService = new GameService();
        // $gameService->getSteamGamesPriceData();

        return redirect()->route('lans.show', $lan);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Lan  $lan
     * @return \Illuminate\Http\Response
     */
    public function show(Lan $lan, Request $request)
    {
        $missing = intval($request->missing);
        $gameService = new GameService();
        $sharedGames = $gameService->sharedGames($lan->users);
        $wishlistSharedGames = $gameService->sharedWishListGames($lan->users);
        $almostSharedGames = ($missing === 0) ? $gameService->almostSharedGames($lan) : $gameService->almostSharedGames($lan, $missing);
        $lanMaterials = LanMaterial::where('lan_id', $lan->id)->get();
        $data = [
            'lan' => $lan,
            'sharedGames' => $sharedGames->sortByDesc(function ($game) use ($lan) {
                return Vote::where('lan_id', $lan->id)->where('game_id', $game->appid)->count();
            }),
            'almostSharedGames' => $almostSharedGames,
            'lanMaterials' => $lanMaterials,
            'wishlistSharedGames' => $wishlistSharedGames
        ];
        return view('lans.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Lan  $lan
     * @return \Illuminate\Http\Response
     */
    public function edit(Lan $lan)
    {
        $data = [
            'friendslist' => $this->userService->getSteamUserFriendlist(Auth::user()),
            'lan' => $lan
        ];
        return view('lans.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Lan  $lan
     * @return \Illuminate\Http\Response
     */
    public function update(StoreLanRequest $request, Lan $lan)
    {
        $lan->update($request->all());
        $lan->users()->detach();
        $lan->users()->attach(Auth::user());
        $players = explode(',', $request->players);
        if (!empty($players[0])) {
            foreach ($players as $player) {
                $user = User::where('steam_id', $player)->first();
                // user doesn't exists in db
                if ($user === null) {
                    $steamUser = $this->userService->getSteamUsersData($player);

                    // create user
                    $user = new User();
                    $user->name = $steamUser[0]['personaname'];
                    $user->avatar = $steamUser[0]['avatar'];
                    $user->steam_id = $steamUser[0]['steamid'];
                    $user->save();

                    // load user's data
                    $user->getSteamGames();
                }
                if (!$lan->users->contains($user)) {
                    $lan->users()->attach($user);
                }
            }
        }
        return redirect()->route('lans.show', $lan);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Lan  $lan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lan $lan)
    {
        $lan->delete();
        return redirect()->route('users.lan');
    }

    public function searchPlayer(Request $request)
    {
        $resultQuery = User::where('name', 'like', '%' . $request->user . '%')->get();
        $data = '';
        foreach ($resultQuery as $result) {
            $data .= '
                <li class="list-group-item contsearch">
                    <a href="javascript:void()" class="search" data-value="' . $result->steam_id . '"><img src="' . $result->avatar . '" alt="' . $result->name . '"></img> ' . $result->name . '</a>
                </li>
            ';
        }
        return $data;
    }

    public function upvoteGame(Request $request)
    {
        $vote = Vote::where('user_id', Auth::user()->id)->where('lan_id', $request->lan)->where('game_id', $request->game)->first();
        if ($vote === null) {
            Vote::create([
                'user_id' => Auth::user()->id,
                'lan_id' => $request->lan,
                'game_id' => $request->game
            ]);
            return true;
        } else {
            return false;
        }
    }

    public function downvoteGame(Request $request)
    {
        return Vote::where('user_id', Auth::user()->id)->where('lan_id', $request->lan)->where('game_id', $request->game)->delete();
    }

    public function addPoint(Request $request)
    {
        $points = DB::table('lan_user')
            ->where('lan_id', $request->lan)
            ->where('user_id', $request->user)
            ->get()[0]->points;

        if ($points === null) {
            $points = 1;
        } else {
            $points++;
        }

        DB::table('lan_user')
            ->where('lan_id', $request->lan)
            ->where('user_id', $request->user)
            ->update(['points'  => $points]);

        return $points;
    }

    public function removePoint(Request $request)
    {
        $points = DB::table('lan_user')
            ->where('lan_id', $request->lan)
            ->where('user_id', $request->user)
            ->get()[0]->points;

        if ($points === null || $points === 0) {
            $points = 0;
        } else {
            $points--;
        }

        DB::table('lan_user')
            ->where('lan_id', $request->lan)
            ->where('user_id', $request->user)
            ->update(['points'  => $points]);

        return $points;
    }

    public function resetPoints(Request $request)
    {
        $lan = Lan::where('id', $request->lan)->first();
        DB::table('lan_user')
            ->where('lan_id', $request->lan)
            ->whereIn('user_id', $lan->users->pluck('id')->toArray())
            ->update(['points'  => 0]);
    }

    public function players(Request $request)
    {
        $lan = Lan::find($request->lan_id);
        return $lan->users;
    }
}

app/Http/Controllers/Lan/Material/LanMaterialController.php
<?php

namespace App\Http\Controllers\Lan\Material;

use App\Http\Controllers\Controller;
use App\Models\Lan;
use App\Models\LanMaterial;
use App\Models\Material;
use App\Models\User;
use http\Env\Response;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class LanMaterialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $materials = Material::all();
        return view('lan_materials.index', compact('materials'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return View
     */
    public function create(Request $request): View
    {
        $lan_id = $request->get('lan_id');
        $material_id = $request->get('material_id');
        $user_id = $request->get('user_id');

        $lan = null;
        $material = null;
        $user = null;

        if (isset($lan_id))
            $lan = Lan::find($lan_id);
        if (isset($material_id))
            $material = Material::find($material_id);
        if (isset($user_id))
            $user = User::find($user_id);

        $materials = Material::all();
        $lans = Lan::all();
        return view('lan_materials.create', compact('materials', 'lans', $lan ? 'lan' : null, $material ? 'material' : null, $user ? 'user' : null));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $inputs = $request->validate([
            'lan_id' => 'required|exists:lans,id',
            'material_id' => 'required|exists:materials,id',
            'user_id' => 'required|exists:users,id',
            'quantity' => 'required',
            'unit' => 'nullable',
        ]);

        $lanMaterial = LanMaterial::create($inputs);

        return redirect()->route('lans.show', $lanMaterial->lan);
    }

    /**
     * Display the specified resource.
     *
     * @param  LanMaterial $lanMaterial
     * @return View
     */
    public function show(LanMaterial $lanMaterial): View
    {
        return view('lan_materials.show', compact('lanMaterial'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  LanMaterial $lanMaterial
     * @return View
     */
    public function edit(LanMaterial $lanMaterial): View
    {
        $lan = Lan::where('id', $lanMaterial->lan_id)->first();
        return view('lan_materials.edit', compact('lanMaterial', 'lan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  LanMaterial $lanMaterial
     * @return RedirectResponse
     */
    public function update(Request $request, LanMaterial $lanMaterial): RedirectResponse
    {
        $input = $request->validate([
            'user_id' => 'required|exists:users,id',
            'quantity' => 'required',
            'unit' => 'nullable',
        ]);
        $lanMaterial->update($input);

        return redirect()->route('lans.show', $lanMaterial->lan);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  LanMaterial $lanMaterial
     * @return RedirectResponse
     */
    public function destroy(LanMaterial $lanMaterial): RedirectResponse
    {
        $lan = $lanMaterial->lan_id;
        $lanMaterial->delete();
        return redirect()->route('lans.show', $lan);
    }
}

resources/views/lans/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Create a new LAN</h1>
    <form action="{{ route('lans.store') }}" method="POST">
        @csrf
        <fieldset>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" aria-describedby="name" value="{{ old('name') }}" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control" id="description" name="description" rows="3">{{ old('description') }}</textarea>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="date_start">Date Start</label>
                        <input type="text" class="form-control date-picker" id="date_start" value="{{ old('date_start') }}" name="date_start" autocomplete="off">
                    </div>
                    <div class="col">
                        <label for="date_end">Date End</label>
                        <input type="text" class="form-control date-picker" id="date_end" value="{{ old('date_end') }}" name="date_end" autocomplete="off">
                    </div>
                </div>
            </div>

            <h4>Players : </h4>
            <ul id="players" style="padding-left: 0;"></ul>

            <label for="friendslist">Friends List</label>
            <ul id="friendslist" style="padding-left: 0;">
                @foreach($friendslist as $friend)
                <li class="list-group-item">
                    <span><img src="{{ $friend['avatar'] }}" alt="{{ $friend['personaname'] }}"> {{ $friend['personaname'] }}</span>
                    <a class="add_friend" data-friend-steamid="{{ $friend['steamid'] }}"><i class="fas fa-user-plus" style="float: right;"></i></a>
                </li>
                @endforeach
            </ul>

            <div class="form-group">
                <label for="user">Add player</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="user" name="user" placeholder="Player's name" autocomplete="off" aria-label="Add player">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" id="reset" type="button"><i class="fas fa-times"></i></button>
                    </div>
                </div>
            </div>
            <ul class="list-group"></ul>
            <br>
            <div id="search"></div>
            <input type="hidden" name="players" id="players_value" value="" />
            <button type="submit" class="btn btn-primary submit">Submit</button>
        </fieldset>
    </form>
</div>
@endsection

@section('scripts')
<script>
    $('.submit').on('click', function() {
        showLoading();
    });

    $('#date_start').datepicker({
        firstDay: 1,
        format: 'yyyy-mm-dd',
    });

    $('#date_end').datepicker({
        firstDay: 1,
        format: 'yyyy-mm-dd',
    });

    function debounce(callback, wait) {
        let timeout;
        return (...args) => {
            clearTimeout(timeout);
            timeout = setTimeout(function() {
                callback.apply(this, args);
            }, wait);
        };
    }

    $('#user').keyup(debounce(() => {
        let username = $('#user').val();
        $('.list-group').css('display', 'block');
        if (username.length == 0) {
            $('.list-group').css('display', 'none');
        } else {
            $.ajax({
                url: "{{ route('lans.player.search') }}",
                method: "POST",
                data: {
                    user: username
                },
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                },
                success: function(data) {
                    $('.list-group').html(data);
                }
            });
        }
    }, 500));

    function reset() {
        $('#user').val('');
        $('#user').prop('disabled', false);
    }

    let players = [];

    $(document).on('click', '.search', function() {
        let username = $(this).text();
        let avatar = $(this).children().attr('src');
        $('#user').val(username);
        $('.list-group').css('display', 'none');

        // on save les ids des users
        let id = $(this).data("value");
        players.push(id);
        $('#players_value').val(players);

        $('#players').append(`
            <li class="list-group-item">
                <span><img src="` + avatar + `" alt="` + username + `"> ` + username + `</span>
                <a class="delete_player" data-player-id="` + id + `"><i class="fas fa-times" style="float: right;"></i></a>
            </li>
        `);
        reset();
    });

    $(document).on('click', '.add_friend', function() {
        let friend_steamid = $(this).data('friend-steamid');
        let username = $(this).parent().children('span').text();
        let avatar = $(this).parent().children('span').children('img').attr('src');
        players.push(friend_steamid);
        $('#players_value').val(players);
        $('#players').append(`
            <li class="list-group-item">
                <span><img src="` + avatar + `" alt="` + username + `"> ` + username + `</span>
                <a class="delete_player" data-player-id="` + friend_steamid + `"><i class="fas fa-times" style="float: right;"></i></a>
            </li>
        `);
        $(this).parent().remove();
    });

    $(document).on('click', '.delete_player', function() {
        let player_id = $(this).data('player-id');
        let username = $(this).parent().children('span').text();
        let avatar = $(this).parent().children('span').children('img').attr('src');
        players = $.grep(players, function(p) {
            return p !== player_id;
        });
        $('#players_value').val(players);
        $('#friendslist').append(`
            <li class="list-group-item">
                <span><img src="` + avatar + `" alt="` + username + `"> ` + username + `</span>
                <a class="add_friend" data-friend-steamid="` + player_id + `"><i class="fas fa-user-plus" style="float: right;"></i></a>
            </li>
        `);
        $(this).parent().remove();
    });

    $('#reset').on('click', function() {
        reset();
    })
</script>
@endsection

resources/views/lans/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Edit {{ $lan->name }}</h1>
    <form action="{{ route('lans.update', $lan) }}" method="POST">
        @csrf
        @method('put')
        <fieldset>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" aria-describedby="name" name="name" value="{{ $lan->name }}" placeholder="{{ $lan->name }}">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control" id="description" name="description" rows="3">{{ $lan->description }}</textarea>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="date_start">Date Start</label>
                        <input type="text" class="form-control date-picker" id="date_start" value="{{ $lan->date_start }}" name="date_start" autocomplete="off">
                    </div>
                    <div class="col">
                        <label for="date_end">Date End</label>
                        <input type="text" class="form-control date-picker" id="date_end" value="{{ $lan->date_end }}" name="date_end" autocomplete="off">
                    </div>
                </div>
            </div>

            <h4>Players : </h4>
            <ul id="players" style="padding-left: 0;">
                @foreach($lan->users as $player)
                <li class="list-group-item">
                    <span><img src="{{ $player->avatar }}" alt="{{ $player->name }}"> {{ $player->name }}</span>
                    <a class="delete_player" data-player-id="{{ $player->steam_id }}"><i class="fas fa-times" style="float: right;"></i></a>
                </li>
                @endforeach
            </ul>

            <label for="friendslist">Friends List</label>
            <ul id="friendslist" style="padding-left: 0;">
                @foreach($friendslist as $friend)
                @if(!$lan->users->contains('steam_id', $friend['steamid']))
                <li class="list-group-item">
                    <span><img src="{{ $friend['avatar'] }}" alt="{{ $friend['personaname'] }}"> {{ $friend['personaname'] }}</span>
                    <a class="add_friend" data-friend-steamid="{{ $friend['steamid'] }}"><i class="fas fa-user-plus" style="float: right;"></i></a>
                </li>
                @endif
                @endforeach
            </ul>

            <div class="form-group">
                <label for="user">Add player</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="user" name="user" placeholder="Player's name" autocomplete="off" aria-label="Add player">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" id="reset" type="button"><i class="fas fa-times"></i></button>
                    </div>
                </div>
            </div>
            <ul class="list-group"></ul>
            <br>
            <div id="search"></div>
            <input type="hidden" name="players" id="players_value" value="" />
            <button type="submit" class="btn btn-primary submit">Submit</button>
        </fieldset>
    </form>
</div>
@endsection

@section('scripts')
<script>
    $('.submit').on('click', function() {
        showLoading();
    });

    let players = [];

    $(document).ready(function() {
        let playersArray = <?php echo json_encode($lan->users) ?>;
        playersArray.forEach(player => {
            players.push(player['steam_id']);
        });
        $('#players_value').val(players);
    });

    $('.date-picker').datepicker({
        constrainInput: true,
        autoSize: true,
        firstDay: 1,
        format: 'yyyy-mm-dd',
        todayHighlight: true,
        autoclose: true
    });

    function debounce(callback, wait) {
        let timeout;
        return (...args) => {
            clearTimeout(timeout);
            timeout = setTimeout(function() {
                callback.apply(this, args);
            }, wait);
        };
    }

    $('#user').keyup(debounce(() => {
        let username = $('#user').val();
        $('.list-group').css('display', 'block');
        if (username.length == 0) {
            $('.list-group').css('display', 'none');
        } else {
            $.ajax({
                url: "{{ route('lans.player.search') }}",
                method: "POST",
                data: {
                    user: username
                },
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                },
                success: function(data) {
                    $('.list-group').html(data);
                }
            });
        }
    }, 500));

    function reset() {
        $('#user').val('');
        $('#user').prop('disabled', false);
    }

    $(document).on('click', '.search', function() {
        let username = $(this).text();
        let avatar = $(this).children().attr('src');
        $('#user').val(username);
        $('.list-group').css('display', 'none');

        // on save les ids des users
        let id = $(this).data("value");
        players.push(id);
        $('#players_value').val(players);

        $('#players').append(`
            <li class="list-group-item">
            <span><img src="` + avatar + `" alt="` + username + `">` + username + `</span>
                <a class="delete_player" data-player-id="` + id + `"><i class="fas fa-times" style="float: right;"></i></a>
            </li>
        `);
        reset();
    });

    $(document).on('click', '.add_friend', function() {
        let friend_steamid = $(this).data('friend-steamid');
        let username = $(this).parent().children('span').text();
        let avatar = $(this).parent().children('span').children('img').attr('src');
        players.push(friend_steamid);
        $('#players_value').val(players);
        $('#players').append(`
        <li class="list-group-item">
            <span><img src="` + avatar + `" alt="` + username + `"> ` + username + `</span>
            <a class="delete_player" data-player-id="` + friend_steamid + `"><i class="fas fa-times" style="float: right;"></i></a>
        </li>
    `);
        $(this).parent().remove();
    });

    $(document).on('click', '.delete_player', function() {
        let player_id = $(this).data('player-id');
        let username = $(this).parent().children('span').text();
        let avatar = $(this).parent().children('span').children('img').attr('src');
        players = $.grep(players, function(p) {
            return p !== player_id;
        });
        $('#players_value').val(players);
        $('#friendslist').append(`
            <li class="list-group-item">
                <span><img src="` + avatar + `" alt="` + username + `"> ` + username + `</span>
                <a class="add_friend" data-friend-steamid="` + player_id + `"><i class="fas fa-user-plus" style="float: right;"></i></a>
            </li>
        `);
        $(this).parent().remove();
    });

    $('#reset').on('click', function() {
        reset();
    })
</script>
@endsection