routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\SteamAuthController;
use App\Http\Controllers\Home\HomeController;
use App\Http\Controllers\Lan\LanController;
use App\Http\Controllers\Lan\Material\LanMaterialController;
use App\Http\Controllers\Lan\Material\MaterialController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return redirect()->route('users.lan');
});
Route::get('/', function () {
    return redirect()->route('users.lan');
});

Route::get('auth/steam', [SteamAuthController::class, 'redirectToSteam'])->name('auth.steam');
Route::get('auth/steam/handle', [SteamAuthController::class, 'handle'])->name('auth.steam.handle');
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::resources([
    'lans'  => LanController::class,
]);

Route::prefix('users')->group(function () {
    Route::get('games', [HomeController::class, 'games'])->name('users.games');
    Route::get('games/wishlist', [HomeController::class, 'wishlist'])->name('users.games.wishlist');
    Route::get('lan', [HomeController::class, 'lan'])->name('users.lan');
    Route::get('data/refresh', [HomeController::class, 'refreshDataUser'])->name('users.data.refresh');
});

Route::prefix('lans')->group(function () {
    Route::prefix('player')->group(function () {
        Route::post('search', [LanController::class, 'searchPlayer'])->name('lans.player.search');
        Route::post('vote/up', [LanController::class, 'upvoteGame'])->name('lans.player.vote.up');
        Route::post('vote/down', [LanController::class, 'downvoteGame'])->name('lans.player.vote.down');
        Route::post('points/add', [LanController::class, 'addPoint'])->name('lans.player.points.add');
        Route::post('points/remove', [LanController::class, 'removePoint'])->name('lans.player.points.remove');
        Route::post('points/reset', [LanController::class, 'resetPoints'])->name('lans.player.points.reset');
        Route::post('', [LanController::class, 'players'])->name('lans.players');
    });
});

Route::resource('materials', MaterialController::class);
Route::resource('lan_materials', LanMaterialController::class);

app/Models/LanMaterial.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class LanMaterial extends Model
{
    use HasFactory;

    protected $fillable = [
        'lan_id',
        'material_id',
        'user_id',
        'quantity',
        'unit',
    ];

    public function lan(): BelongsTo
    {
        return $this->belongsTo(Lan::class);
    }

    public function material(): BelongsTo
    {
        return $this->belongsTo(Material::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Lan/Material/LanMaterialController.php
<?php

namespace App\Http\Controllers\Lan\Material;

use App\Http\Controllers\Controller;
use App\Models\Lan;
use App\Models\LanMaterial;
use App\Models\Material;
use App\Models\User;
use http\Env\Response;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class LanMaterialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $materials = Material::all();
        return view('lan_materials.index', compact('materials'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return View
     */
    public function create(Request $request): View
    {
        $lan_id = $request->get('lan_id');
        $material_id = $request->get('material_id');
        $user_id = $request->get('user_id');

        $lan = null;
        $material = null;
        $user = null;

        if (isset($lan_id))
            $lan = Lan::find($lan_id);
        if (isset($material_id))
            $material = Material::find($material_id);
        if (isset($user_id))
            $user = User::find($user_id);

        $materials = Material::all();
        $lans = Lan::all();
        return view('lan_materials.create', compact('materials', 'lans', $lan ? 'lan' : null, $material ? 'material' : null, $user ? 'user' : null));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $inputs = $request->validate([
            'lan_id' => 'required|exists:lans,id',
            'material_id' => 'required|exists:materials,id',
            'user_id' => 'required|exists:users,id',
            'quantity' => 'required',
            'unit' => 'nullable',
        ]);

        $lanMaterial = LanMaterial::create($inputs);

        return redirect()->route('lans.show', $lanMaterial->lan);
    }

    /**
     * Display the specified resource.
     *
     * @param  LanMaterial $lanMaterial
     * @return View
     */
    public function show(LanMaterial $lanMaterial): View
    {
        return view('lan_materials.show', compact('lanMaterial'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  LanMaterial $lanMaterial
     * @return View
     */
    public function edit(LanMaterial $lanMaterial): View
    {
        $lan = Lan::where('id', $lanMaterial->lan_id)->first();
        return view('lan_materials.edit', compact('lanMaterial', 'lan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  LanMaterial $lanMaterial
     * @return RedirectResponse
     */
    public function update(Request $request, LanMaterial $lanMaterial): RedirectResponse
    {
        $input = $request->validate([
            'user_id' => 'required|exists:users,id',
            'quantity' => 'required',
            'unit' => 'nullable',
        ]);
        $lanMaterial->update($input);

        return redirect()->route('lans.show', $lanMaterial->lan);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  LanMaterial $lanMaterial
     * @return RedirectResponse
     */
    public function destroy(LanMaterial $lanMaterial): RedirectResponse
    {
        $lan = $lanMaterial->lan_id;
        $lanMaterial->delete();
        return redirect()->route('lans.show', $lan);
    }
}

resources/views/lan_materials/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Add material to LAN for User</h1>
        <form action="{{ route('lan_materials.store') }}" method="POST">
            @csrf
            <fieldset>
                <div class="form-group">
                    <label for="lan_id">Select LAN</label>
                    <select class="form-control" id="lan_id" name="lan_id">
                        <option value>...</option>
                        @foreach($lans as $l)
                            <option value="{{ $l->id }}" @if(isset($lan) && $l->id == $lan->id)selected @endif>{{ $l->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="material_id">Select Material</label>
                    <select class="form-control" id="material_id" name="material_id">
                        <option value>...</option>
                        @foreach($materials as $m)
                            <option value="{{ $m->id }}" @if(isset($material) && $m->id == $material->id)selected @endif>{{ $m->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="user_id">Select User</label>
                    <select class="form-control" id="user_id" name="user_id">
                        <option value>...</option>
                        @isset($lan)
                            @foreach ($lan->users as $u)
                                <option value="{{ $u->id }}" @if(isset($user) && $u->id == $user->id)selected @endif>{{ $u->name }}</option>
                            @endforeach
                        @endisset
                    </select>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label for="quantity">Quantity</label>
                            <input type="number" class="form-control" id="quantity" value="{{ old('quantity') }}" name="quantity" autocomplete="off">
                        </div>
                        <div class="col">
                            <label for="unit">Unit</label>
                            <input type="text" class="form-control" id="unit" value="{{ old('unit') }}" name="unit" autocomplete="off">
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary submit">Submit</button>
            </fieldset>
        </form>
    </div>
@endsection

@section('scripts')
    <script>
        $('#lan_id').on('change', function() {
            if($('#lan_id').val()) {
                let lan_select = $('#lan_id');
                let lan_id = lan_select.val();
                $.ajax({
                    url: "{{ route('lans.players') }}",
                    data: {
                        'lan_id': lan_id
                    },
                    type: 'POST',
                    headers: {
                        'X-CSRF-TOKEN': "{{ csrf_token() }}"
                    }
                })
                .done(function(data) {
                    var el = $("#user_id");
                    el.empty(); // remove old options
                    data.forEach(function(index, option) {
                        $option = $("<option></option>")
                            .attr("value", index.id)
                            .text(index.name);
                        el.append($option);
                    });
                })
            } else {
                var el = $("#user_id");
                el.empty(); // remove old options
                $option = $("<option></option>")
                    .attr("value", null)
                    .text("...");
                el.append($option);
            }
        });
    </script>
@endsection

resources/views/lan_materials/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Edit lan material</h1>
        <form action="{{ route('lan_materials.update', $lanMaterial) }}" method="POST">
            <input type="hidden" name="_method" value="PATCH">
            @csrf
            <fieldset>
                <div class="form-group">
                    <label for="user_id">Select User</label>
                    <select class="form-control" id="user_id" name="user_id">
                        @forelse ($lan->users as $u)
                            <option value="{{ $u->id }}"
                                    @if($u->id == $lanMaterial->user_id)selected @endif>{{ $u->name }}</option>
                        @empty
                        @endforelse
                    </select>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label for="quantity">Quantity</label>
                            <input type="number" class="form-control" id="quantity" value="{{ $lanMaterial->quantity }}"
                                   name="quantity" autocomplete="off">
                        </div>
                        <div class="col">
                            <label for="unit">Unit</label>
                            <input type="text" class="form-control" id="unit" value="{{ $lanMaterial->unit }}" name="unit"
                                   autocomplete="off">
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary submit">Submit</button>
            </fieldset>
        </form>
    </div>
@endsection

resources/views/lan_materials/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>
            {{ $lanMaterial->material->name }} <a href="{{ route('lan_materials.edit', $lanMaterial) }}"><small><i class="fas fa-pencil-alt"></i></small></a>
            <small class="text-muted">{{ $lanMaterial->lan->name }} -> {{ ucfirst($lanMaterial->lan->date_start->translatedFormat('d F Y')) }} to {{ ucfirst($lanMaterial->lan->date_end->translatedFormat('d F Y')) }}</small>
        </h3>
        <div class="row">
            <div class="col-12">
                {{ $lanMaterial->quantity }} {{ $lanMaterial->unit }}
            </div>
            <div class="col-12">
                Taken by : {{ $lanMaterial->user->name }}
            </div>
        </div>
@endsection